// Gerado a partir de data/paises.json (fallback offline).
const paisesFallback = <List<String>>[
  ["DE", "Alemanha"],
  ["AR", "Argentina"],
  ["AU", "Austrália"],
  ["BO", "Bolívia"],
  ["BR", "Brasil"],
  ["BE", "Bélgica"],
  ["KH", "Camboja"],
  ["CA", "Canadá"],
  ["CL", "Chile"],
  ["CN", "China"],
  ["CO", "Colômbia"],
  ["KR", "Coreia do Sul"],
  ["CR", "Costa Rica"],
  ["HR", "Croácia"],
  ["EG", "Egito"],
  ["AE", "Emirados Árabes Unidos"],
  ["EC", "Equador"],
  ["ES", "Espanha"],
  ["US", "Estados Unidos"],
  ["PH", "Filipinas"],
  ["FR", "França"],
  ["GR", "Grécia"],
  ["HU", "Hungria"],
  ["ID", "Indonésia"],
  ["IE", "Irlanda"],
  ["IS", "Islândia"],
  ["IT", "Itália"],
  ["JP", "Japão"],
  ["MY", "Malásia"],
  ["MA", "Marrocos"],
  ["MX", "México"],
  ["NP", "Nepal"],
  ["NO", "Noruega"],
  ["NZ", "Nova Zelândia"],
  ["PY", "Paraguai"],
  ["NL", "Países Baixos"],
  ["PE", "Peru"],
  ["PL", "Polônia"],
  ["PT", "Portugal"],
  ["KE", "Quênia"],
  ["GB", "Reino Unido"],
  ["SG", "Singapura"],
  ["CH", "Suíça"],
  ["TH", "Tailândia"],
  ["CZ", "Tchéquia"],
  ["TR", "Turquia"],
  ["UY", "Uruguai"],
  ["VN", "Vietnã"],
  ["ZA", "África do Sul"],
  ["AT", "Áustria"],
  ["IN", "Índia"],
];
